apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  labels:
    ctfd: mysql-pv
    app: db-pv
  name: db-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  labels:
    ctfd: mysql
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ctfd: mysql
        app: db
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --wait_timeout=28800
        - --log-warnings=0
        env:
        - name: MYSQL_DATABASE
          value: ctfd
        - name: MYSQL_PASSWORD
          value: ctfd
        - name: MYSQL_ROOT_PASSWORD
          value: ctfd
        - name: MYSQL_USER
          value: ctfd
        image: mariadb:10.4.12
        imagePullPolicy: "Always"
        name: db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-pv
      restartPolicy: Always
      volumes:
      - name: db-pv
        persistentVolumeClaim:
          claimName: db-pv
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: ClusterIP
