apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  name: cache-pv
  labels:
    ctfd: redis-pv
    app: cache-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  name: cache
  labels:
    ctfd: redis
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ctfd: redis
        app: cache
    spec:
      containers:
      - image: redis:4
        imagePullPolicy: "Always"
        name: cache
        volumeMounts:
        - mountPath: /data
          name: cache-pv
      restartPolicy: Always
      volumes:
      - name: cache-pv
        persistentVolumeClaim:
          claimName: cache-pv
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctfdaemon
  creationTimestamp: null
  labels:
    app: cache
  name: cache
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: cache
  type: ClusterIP
